version: '2'

services:

  #######################################
  # Align AUXIP to LTA: ingest missing 
 #######################################
  lta_auxip_align_S1:
    extends: 
      file: docker-compose.yml
      service: prip_ingestion_s2
    container_name: lta_auxip_align_S1
    image: lta_auxip_align:1.0.2
    environment:
      LTA_ALIGN_BATCH_LEN: 12
      L0_ALIGN_START: "2022-04-01"
      ALIGN_MISSION: "S1"
    volumes:
      - /adg_data/grib2/lta_auxip_align:/lta_auxip_align
    restart: no

  lta_auxip_align_S2:
    extends: 
      file: docker-compose.yml
      service: prip_ingestion_s2
    container_name: lta_auxip_align_S2
    image: lta_auxip_align:1.0.2
    environment:
      LTA_ALIGN_BATCH_LEN: 12
      L0_ALIGN_START: "2022-04-01"
      ALIGN_MISSION: "S2"
    volumes:
      - /adg_data/grib2/lta_auxip_align:/lta_auxip_align
    restart: no

  lta_auxip_align_S3:
    extends: 
      file: docker-compose.yml
      service: prip_ingestion_s2
    container_name: lta_auxip_align_S3
    image: lta_auxip_align:1.0.2
    environment:
      LTA_ALIGN_BATCH_LEN: 5
      L0_ALIGN_START: "2022-04-01"
      ALIGN_MISSION: "S3"
    volumes:
      - /adg_data/grib2/lta_auxip_align:/lta_auxip_align
    restart: no



