version: '2'

services:

  #######################################
  # Align AUXIP to LTA: ingest missing 
 #######################################
  lta_auxip_align:
    extends: 
      file: docker-compose.yml
      service: prip_ingestion_s2
    container_name: lta_auxip_align
    image: lta_auxip_align:1.0.1
    environment:
      LTA_ALIGN_BATCH_LEN: 12
      L0_ALIGN_START: "2022-04-01"
    volumes:
      - /adg_data/grib2/lta_auxip_align:/lta_auxip_align
    restart: no



